server:
  servlet:
    context-path: /db
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bakery
    username: postgres
    password: 111111
    driver-class-name: org.postgresql.Driver

mybatis:
  type-aliases-package: com.junlan.bean
  mapper-locations: classpath:mapper/*.xml